# fly.toml file generated for cache on 2021-05-07T21:26:24+02:00

app = "cache"

kill_signal = "SIGINT"
kill_timeout = 5

[[mounts]]
source      = "redis_server"
destination = "/data"

[env]
  PRIMARY_REGION = "lhr"

[experimental]
  auto_rollback = true
  private_network= true

[[services]]
  internal_port = 6379
  protocol      = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = 10000
    timeout  = 2000